/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YopUlvyy4wx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

export function Component() {
  return (
    <>
      <main className="flex-1 mx-auto max-w-[100vw]">
        <section className="py-12 ">
          <div className="px-4 md:px-6 gap-6  lg:gap-12 flex xl:flex-row flex-col  ">
            <div className="flex flex-col justify-center space-y-4 h-[400px] xl:w-1/2 w-full">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-5xl/none">
                  Elevate Your Ride with Superior Performance
                </h1>
                <p className="max-w-[600px] text-muted-foreground md:text-[17px]">
                  At Motodrager, we provide high-performance engine oils, brake fluids, and essential vehicle fluids to keep your car or bike running smoothly. Designed to enhance performance and extend lifespan, our products ensure top-tier reliability for both daily drivers and high-performance machines.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Contact Now
                </Link>
              </div>
            </div>
            <div className="xl:w-1/2 w-full flex justify-center">
              <img
                src="https://gomechanic.in/blog/wp-content/uploads/2020/03/Oil-Change-2.jpg"
                alt="Hero"
                className=" h-[400px] object-cover rounded-xl"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-24  ">
          <div className="container mx-auto px-4 md:px-6 grid gap-6 lg:gap-12 h-fit">
            <div className="flex flex-col justify-center space-y-4 wful">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-center">Key Stats</h2>
                <p className=" text-muted-foreground md:text-[17px] lg:text-base/relaxed text-center">
                  Check out some of our key stats and see why Motodrager is the leading provider of high-quality
                  lubricants.
                </p>
              </div>
              <div className="grid xl:grid-cols-4 xl:grid-row- md:grid-cols-2 gap-4 h-fit">
                <Card>
                  <CardHeader className="flex flex-row items-center justify-between pb-2">
                    <CardTitle className="text-sm font-medium">Years in Business</CardTitle>
                    <CalendarDaysIcon />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">8+</div>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="flex flex-row items-center justify-between pb-2">
                    <CardTitle className="text-sm font-medium">Satisfied Customers</CardTitle>
                    <UsersIcon />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">10,000+</div>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="flex flex-row items-center justify-between pb-2">
                    <CardTitle className="text-sm font-medium">Products Sold</CardTitle>
                    <BoxIcon />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">200,000+</div>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="flex flex-row items-center justify-between pb-2">
                    <CardTitle className="text-sm font-medium">Authorized Dealer</CardTitle>
                    <MapPinIcon />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">25+</div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12">
          <div className=" px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Our Top Products</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Lubricate Inc offers a wide range of high-quality car and bike lubricants to keep your vehicle running
                  smoothly.
                </p>
              </div>
            </div>
            <div className="mx-auto flex flex-wrap justify-center gap-6 py-12 ">
              <div className="flex flex-col items-center justify-between space-y-4 rounded-lg border bg-background p-6 shadow-sm">
                <img
                  src="/placeholder.svg"
                  alt="Product"
                  className="mx-auto  overflow-hidden rounded-md object-cover h-[400px] w-full "
                />
                <div className="space-y-2 text-center">
                  <h3 className="text-lg font-medium">Engine Oil</h3>
                  <p className="text-sm text-muted-foreground">
                    Our premium engine oil keeps your engine running smoothly.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center justify-between space-y-4 rounded-lg border bg-background p-6 shadow-sm">
                <img
                  src="/placeholder.svg"
                  alt="Product"
                  className="mx-auto overflow-hidden rounded-md object-cover h-[400px] w-full"
                />
                <div className="space-y-2 text-center">
                  <h3 className="text-lg font-medium">Engine Oil</h3>
                  <p className="text-sm text-muted-foreground">
                    Our premium engine oil keeps your engine running smoothly.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center justify-between space-y-4 rounded-lg border bg-background p-6 shadow-sm">
                <img
                  src="/placeholder.svg"
                  alt="Product"
                  className="mx-auto overflow-hidden rounded-md object-cover h-[400px] w-full"
                />
                <div className="space-y-2 text-center">
                  <h3 className="text-lg font-medium">Engine Oil</h3>
                  <p className="text-sm text-muted-foreground">
                    Our premium engine oil keeps your engine running smoothly.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-4 md:px-6 space-y-6">
            <div className="space-y-4 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Why Choose Acme Inc.</h2>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                At Acme Inc., we pride ourselves on our commitment to innovation, excellence, and customer satisfaction.
                Here are a few reasons why you should choose us:
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <div className="flex flex-col items-center space-y-2">
                <RocketIcon />
                <div className="space-y-1 text-center">
                  <h3 className="text-xl font-semibold">Cutting-Edge Technology</h3>
                  <p className="text-muted-foreground">
                    Our team of experts is constantly exploring the latest advancements in technology to deliver
                    innovative solutions that drive your business forward.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <UsersIcon2 />
                <div className="space-y-1 text-center">
                  <h3 className="text-xl font-semibold">Dedicated Support</h3>
                  <p className="text-muted-foreground">
                    Our customer support team is available around the clock to ensure that your needs are met and your
                    questions are answered promptly.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <BoltIcon />
                <div className="space-y-1 text-center">
                  <h3 className="text-xl font-semibold">Unparalleled Reliability</h3>
                  <p className="text-muted-foreground">
                    Our robust infrastructure and rigorous testing processes ensure that our solutions are reliable,
                    scalable, and secure, giving you peace of mind.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#212124]">
          <div className="container mx-auto px-4 md:px-6 space-y-6 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Thank you for visiting Acme Inc.
            </h2>
            <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              We appreciate your interest in our company and hope you found the information on our website helpful. If you
              have any further questions or would like to learn more about our services, please don&apos;t hesitate to reach
              out. We look forward to the opportunity to work with you.
            </p>
          </div>
        </section>
      </main>
    </>
  )
}

function BoxIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  )
}


function CalendarDaysIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  )
}


function MapPinIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}




function UsersIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}

function BoltIcon() {
  return (
    <svg

      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
      <circle cx="12" cy="12" r="4" />
    </svg>
  )
}


function RocketIcon() {
  return (
    <svg

      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  )
}


function UsersIcon2() {
  return (
    <svg

      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
